### ISSUE TITLE
Unable to open the generated file

### ISSUE THREAD

**Issue by mudrd8mz** [ecampbell/moodle-local_glossary_wordimport#2]
When trying to open the generated *.doc file in LibreOffice 6.4.3.2, it does not work and the source code XHTML is opened. This happens even if I rename the file to have *.docx extension (should not it by the way?)

![image](https://user-images.githubusercontent.com/85831/91472505-d5a09c80-e897-11ea-9727-0b243d32a3d3.png)

**Comment by ecampbell** [comment]
This is not a bug. The plugin generates an XHTML file with extra markup which can only be opened by Microsoft Word. It is then interpreted into a standard Word format. The exported file cannot be opened in any other word-processors. The file suffix is set to .doc for end-user convenience, in order to get Word to open it automatically. Ideally the export would generate a .docx formatted file (Zipped XML), but this is something for the future.
